### ISSUE TITLE
Tutorial requires clack-v1-compat, but this is not explained.

### ISSUE THREAD

**Issue by christophejunke** [clack/clack.github.com#15]
The section 6 (http://clacklisp.org/tutorial/06-using-clack-app-directory.html) mentions `clack.app.directory` which is not available without the compatibility system. This posed a problem recently to a novice following through the tutorial (http://stackoverflow.com/q/39074260/124319). 

A simple fix would be to mention `clack-v1-compat` at the start of the tutorial.

**Comment by fukamachi** [comment]
The tutorial is obsolete and it's not linked from http://clacklisp.org anymore.
New one that compatible with v2 isn't ready yet, however, [Lack's README](https://github.com/fukamachi/lack) may help you somehow.
